spring:
  session:
    timeout: 24h
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  # Spring database configurations
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false

server:
  port: 8080

secret:
  # AES key for enc/dec
  aes-key: AES_KEY